swag init //to create a swagger documentation
git init
git add .
git commit -m "try changes gorm to pgx"
git remote add origin https://github.com/art9276/realEstate.git
git pull origin master
git push origin master